# Generated by Django 4.1.5 on 2023-02-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='item_pic',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
