# Generated by Django 4.1.5 on 2023-04-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
