# Generated by Django 4.2 on 2023-04-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_review_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='whislist',
            new_name='wishlist',
        ),
    ]
