# Generated by Django 4.2 on 2023-04-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_whislist_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
