# Generated by Django 4.2 on 2023-04-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_wishlist_category_name_wishlist_item_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
