# Generated by Django 4.2 on 2023-04-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_wishlist_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='category_name',
        ),
    ]
