# Generated by Django 4.2 on 2023-04-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_wishlist_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='category_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
            preserve_default=False,
        ),
    ]
