# Generated by Django 4.2 on 2023-05-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_orders_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('order processing', 'order processing'), ('order on the way', 'order confirm'), ('order completed', 'order on the way'), ('order recived', 'order recived'), ('order cancelled', 'order cancelled')], max_length=50),
        ),
    ]
