# Generated by Django 4.2 on 2023-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_orders_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='user_details',
            name='lname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='state',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
