# Generated by Django 4.2 on 2023-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_name_user_details_fname_user_details_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
