# Generated by Django 4.2 on 2023-05-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_user_details_address_alter_user_details_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
