# Generated by Django 4.2 on 2023-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_item_item_description_item_original_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='original_rate',
            field=models.FloatField(),
        ),
    ]
