# Generated by Django 4.2 on 2023-05-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_item_original_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
