# Generated by Django 4.2 on 2023-05-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_delete_payment_details_delete_userlogin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offer',
        ),
    ]
