# Generated by Django 4.2.1 on 2023-05-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('order processing', 'order processing'), ('order confirmed', 'order confirmed'), ('order on the way', 'order on the way'), ('order received', 'order received'), ('order cancelled', 'order cancelled')], max_length=50),
        ),
        migrations.CreateModel(
            name='Order_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_details')),
            ],
        ),
    ]
